{{- define "druid.nodeSpec" -}}
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              {{- with .podLabels | merge .root.Values.spec.podLabels }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
              app: druid
              component: {{ .nodeType }}
              druid_cr: {{ include "druid.fullname" .root }}
              nodeSpecUniqueStr: druid-{{ include "druid.fullname" .root }}-{{ .nodeCategory }}
          topologyKey: kubernetes.io/hostname
        weight: 1
druid.port: {{ .druidPort }}
{{- with .env }}
env: {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .envFrom }}
envFrom: {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .extraJvmOptions }}
extra.jvm.options: {{ . | join " " }}
{{- end }}
{{- if .hpAutoscaler }}
hpAutoscaler: {{- toYaml .hpAutoscaler | nindent 2 }}
{{- else if .autoscaling }}
hpAutoscaler:
  {{- with .autoscaling}}
  {{- with .replicas }}
  {{- with .max }}
  maxReplicas: {{ . | int }}
  {{- end }}
  {{- with .min }}
  minReplicas: {{ . | int }}
  {{- end }}
  {{- end }}
  {{- with .metrics }}
  metrics: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .kind | default (and (empty .storage) (empty .volumeClaimTemplates) | ternary "Deployment" "StatefulSet") }}
    name: druid-{{ include "druid.fullname" .root }}-{{ .nodeCategory }}
{{- end }}
{{- with .jvmOptions }}
jvm.options: {{ . | join " " }}
{{- end }}
kind: {{ .kind | default (and (empty .storage) (empty .volumeClaimTemplates) | ternary "Deployment" "StatefulSet") }}
nodeConfigMountPath: {{ .nodeConfigMountPath }}
{{- with .nodeSelector }}
nodeSelector: {{- toYaml . | nindent 2 }}
{{- end }}
nodeType: {{ .nodeType }}
{{- with .podAnnotations }}
podAnnotations: {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .podDisruptionBudget }}
podDisruptionBudgetSpec: {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .podLabels }}
podLabels: {{- toYaml . | nindent 2 }}
{{- end }}
replicas: {{ .replicas }}
{{- with .resources }}
resources: {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .services }}
services: {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .volumeClaimTemplates }}
volumeClaimTemplates: {{- toYaml .volumeClaimTemplates | nindent 2 }}
{{- else }}
{{- with .storage }}
volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .size | default $.root.Values.global.defaultStorageSize }}
      storageClassName: {{ .class | default $.root.Values.global.defaultStorageClass }}
{{- end }}
{{- end }}
{{- with .unsupported }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end -}}

{{- with $.Values.spec }}
{{- $metadataStorage := .metadataStorage }}
{{- $extensionLoadList := list }}
{{- $nonCoreExtensionGroupAndArtifactIds := list }}
{{- range $groupId, $artifactIds := .extensions }}
{{- $extensionLoadList = $artifactIds | concat $extensionLoadList }}
{{- if ne $groupId "org.apache.druid.extensions" }}
{{- range $artifactId := $artifactIds }}
{{- $nonCoreExtensionGroupAndArtifactIds = print $groupId ":" $artifactId | append $nonCoreExtensionGroupAndArtifactIds }}
{{- end }}
{{- end }}
{{- end }}
{{- range $_ := tuple "postgresql" "mysql" }}
{{- if eq $metadataStorage.type . }}
{{- $extensionLoadList = print . "-metadata-storage" | append $extensionLoadList }}
{{- end }}
{{- end }}
{{- $extensionLoadList = $extensionLoadList | uniq | sortAlpha }}
{{- $nonCoreExtensionGroupAndArtifactIds = $nonCoreExtensionGroupAndArtifactIds | uniq | sortAlpha }}
---
apiVersion: druid.apache.org/v1alpha1
kind: Druid
metadata:
  labels: {{- include "druid.labels" $ | nindent 4 }}
  name: {{ include "druid.fullname" $ }}
spec:
  {{- if $nonCoreExtensionGroupAndArtifactIds }}
  additionalContainer:
    - command:
        - bash
        - -c
        - |
          set -o errexit
          cp -r /opt/druid/extensions /
          exec ./bin/run-java \
            -classpath "lib/*" \
            -Ddruid.extensions.directory=/extensions \
            org.apache.druid.cli.Main tools pull-deps \
            {{- range $extensionGroupAndArtifactId := $nonCoreExtensionGroupAndArtifactIds }}
            -c {{ $extensionGroupAndArtifactId }} \
            {{- end }}
            --defaultVersion {{ $.Chart.AppVersion }}
      containerName: pull-deps
      {{- with .image }}
      image: {{ .repository }}:{{ .tag | default $.Chart.AppVersion }}
      {{- end }}
      runAsInit: true
      volumeMounts:
        - mountPath: /extensions
          name: extensions
  {{- end }}
  {{- with .affinity }}
  affinity: {{- toYaml . | nindent 4 }}
  {{- end }}
  common.runtime.properties: |
    druid.discovery.k8s.clusterIdentifier={{ include "druid.fullname" $ }}
    druid.discovery.type=k8s
    druid.extensions.loadList={{ toRawJson $extensionLoadList }}
    {{- with .s3.logs }}
    druid.indexer.logs.disableAcl={{ .disableAcls }}
    druid.indexer.logs.s3Bucket={{ .bucket | default (include "druid.fullname" $) }}
    druid.indexer.logs.s3Prefix={{ .prefix | default (include "druid.name" $ | printf "%s-logs") }}
    druid.indexer.logs.type=s3
    {{- end }}
    {{- include "druid._properties" (dict "dict" .metadataStorage "prefix" "druid.metadata.storage.") | nindent 4 }}
    {{- with .s3.segments }}
    druid.storage.baseKey={{ .prefix | default (include "druid.name" $) }}
    druid.storage.bucket={{ .bucket | default (include "druid.fullname" $) }}
    druid.storage.disableAcl={{ .disableAcls }}
    druid.storage.type=s3
    {{- end }}
    druid.zk.service.enabled=false
    {{- include "druid.properties" .commonRuntimeProperties | nindent 4 }}
  commonConfigMountPath: /opt/druid/conf/druid/cluster/_common
  containerSecurityContext:
    readOnlyRootFilesystem: true
  deleteOrphanPvc: {{ .deleteOrphanPvc }}
  disablePVCDeletionFinalizer: {{ .disablePVCDeletionFinalizer }}
  env:
    {{- if .env }}
    {{- toYaml .env | nindent 4 }}
    {{- else }}
    {{- with .extraEnv }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if ge (.image.tag | default $.Chart.AppVersion | semver).Major 33 }}
    {{- /* https://github.com/apache/druid/releases/tag/druid-33.0.0#33.0.0-upgrade-notes-and-incompatible-changes-upgrade-notes-kubernetes-deployments */}}
    - name: DRUID_SET_HOST_IP
      value: "1"
    {{- end }}
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    {{- end }}
  envFrom:
    {{- if .envFrom }}
    {{- toYaml .envFrom | nindent 4 }}
    {{- else }}
    {{- with .extraEnvFrom }}
    {{- toYaml .| nindent 4 }}
    {{- end }}
    - secretRef:
        name: {{ include "druid.fullname" $ }}
    {{- end }}
  {{- with .extraCommonConfig }}
  extraCommonConfig: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .image }}
  image: {{ .repository }}:{{ .tag | default $.Chart.AppVersion }}
  {{- with .pull }}
  {{- with .policy }}
  imagePullPolicy: {{ . }}
  {{- end }}
  {{- with .secrets }}
  imagePullSecrets: {{ . }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with .jvmOptions }}
  jvm.options: {{ . | join " " }}
  {{- end }}
  {{- with .log4jConfig }}
  log4j.config: |-
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .metricDimensions }}
  metricDimensions.json: |-
    {{- toPrettyJson . | nindent 4 }}
  {{- end }}
  {{- with .nodeSelector }}
  nodeSelector: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .nodes }}
  nodes:
    {{- range $nodeCategory, $_ := . }}
    {{- if and (eq .nodeType "broker") (.replicas | int | lt 0) }}
    {{- with dict "nodeCategory" $nodeCategory | merge . }}
    {{ $nodeCategory }}:
      {{- with .runtimeProperties }}
      runtime.properties: |
        {{- include "druid.properties" . | nindent 8 }}
      {{- end }}
      {{- dict "root" $ | merge . | include "druid.nodeSpec" | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- range $nodeCategory, $_ := . }}
    {{- if and (eq .nodeType "coordinator") (.replicas | int | lt 0) }}
    {{- with dict "nodeCategory" $nodeCategory | merge . }}
    {{ $nodeCategory }}:
      runtime.properties: |
        druid.coordinator.asOverlord.enabled=true
        druid.coordinator.asOverlord.overlordService=druid/overlord
        druid.coordinator.startDelay=PT30S
        druid.indexer.runner.namespace={{ $.Release.Namespace }}
        druid.indexer.runner.type=k8s
        {{- if $metadataStorage }}
        druid.indexer.storage.type=metadata
        {{- end }}
        druid.indexer.task.encapsulatedTask=true
        {{- include "druid.properties" .runtimeProperties | nindent 8 }}
      {{- /*
        The peons will inherit this probe from the overlord, but they don't share the same endpoints, so we have to
        effectively disable it - see
        https://druid.apache.org/docs/latest/development/extensions-contrib/k8s-jobs#overlord-single-container-pod-adapteroverlord-multi-container-pod-adapter
      */}}
      startUpProbe:
        exec:
          command: [ /bin/true ]
        initialDelaySeconds: 0
      {{- dict "root" $ | merge . | include "druid.nodeSpec" | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- range $nodeCategory, $_ := . }}
    {{- if and (eq .nodeType "historical") (.replicas | int | lt 0) }}
    {{- with dict "nodeCategory" $nodeCategory | merge . }}
    {{ $nodeCategory }}:
      runtime.properties: |
        {{- with .storage }}
        druid.segmentCache.locations=[ { "freeSpacePercent": {{ .freeSpacePercent }}, "maxSize": "{{ .size | default $.Values.global.defaultStorageSize }}", "path": "/druid/data/segments" } ]
        {{- end }}
        {{- include "druid.properties" .runtimeProperties | nindent 8 }}
      {{- dict "root" $ | merge . | include "druid.nodeSpec" | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- range $nodeCategory, $_ := . }}
    {{- if and (eq .nodeType "router") (.replicas | int | lt 0) }}
    {{- with dict "nodeCategory" $nodeCategory | merge . }}
    {{ $nodeCategory }}:
      {{- with .runtimeProperties }}
      runtime.properties: |
        {{- include "druid.properties" . | nindent 8 }}
      {{- end }}
      {{- dict "root" $ | merge . | include "druid.nodeSpec" | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  podAnnotations: {{- toYaml .podAnnotations | nindent 4 }}
  podLabels: {{- toYaml .podLabels | nindent 4 }}
  scalePvcSts: true
  securityContext:
    {{- /* uid 1000 == user druid */}}
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  serviceAccount: {{ include "druid.serviceAccountName" $ }}
  {{- with .services }}
  services: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .tolerations }}
  tolerations: {{- toYaml . | nindent 4 }}
  {{- end }}
  volumeMounts:
    - mountPath: /druid/data
      name: data
    {{- if $nonCoreExtensionGroupAndArtifactIds }}
    - mountPath: /opt/druid/extensions
      name: extensions
      readOnly: true
    {{- end }}
    - mountPath: /tmp
      name: tmp
    - mountPath: /opt/druid/var
      name: var
  volumes:
    - emptyDir: { }
      name: data
    {{- if $nonCoreExtensionGroupAndArtifactIds }}
    - emptyDir: { }
      name: extensions
    {{- end }}
    - emptyDir: { }
      name: tmp
    - emptyDir: { }
      name: var
  {{- if .volumeClaimTemplates }}
  {{- with .volumeClaimTemplates }}
  volumeClaimTemplates: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- else }}
  {{- with .storage }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .size | default $.Values.global.defaultStorageSize }}
        storageClassName: {{ .class | default $.Values.global.defaultStorageClass }}
  {{- end }}
  {{- end }}
  {{- with .unsupported }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
