apiVersion: v2
dependencies:
  - name: druid
    repository: file://../druid
    version: ^0.9.1-SNAPSHOT
  - condition: operator.enabled
    alias: operator
    name: druid-operator
    repository: https://charts.deep.bi
    version: ^0.4.0
  - condition: metricsServer.enabled
    alias: metricsServer
    name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server
    version: ^3.13.0
  - condition: minio.enabled
    name: minio
    repository: https://charts.bitnami.com/bitnami
    version: ^17.0.21
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ^18.4.0
description: A Helm chart for deploying Apache Druid in a development environment.
home: https://github.com/bsure-analytics/druid-charts
keywords:
  - Apache Druid
  - Druid
  - development
  - dev
maintainers:
  - name: Christian Schlichtherle
    url: https://github.com/christian-schlichtherle
name: druid-dev
sources:
  - https://github.com/bsure-analytics/druid-charts/charts/druid-dev/tree/main
version: 0.9.1-SNAPSHOT
